### ISSUE TITLE
Trained weights

### ISSUE THREAD

**Issue by JovinLeong** [Atif-Anwer/SHMGAN#1]
Hi, are the trained weights from the paper available?

**Comment by Atif-Anwer** [comment]
Hi Leong!

Thankyou for taking interest in the paper. Unfortunately, at the moment I cannot provide the trained weights as I dont have access to them at the moment as the work is still in progress. 

Thanks again!

**Comment by JovinLeong** [comment]
Hi Anwer, thanks for your reply! 
Understood - so in that case, to reproduce your results, the idea would be for us to retrain the model on the PSD and SHIQ datasets?

**Comment by Atif-Anwer** [comment]
Yes, that would be the ideal way. It should train without any errors hopefully if you run it on a single GPU, since it wasnt coded for multi-gpu configurations..
